# Generated by Django 4.1.1 on 2022-09-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('primary_color', models.CharField(choices=[('Black', 'black'), ('White', 'white'), ('Gold', 'gold'), ('Silver', 'silver'), ('Brown', 'brown')], default='Black', max_length=15)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
